from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Define modules
module gencode:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/gencode/main/workflow/Snakefile"
    config:
        config


module genome:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/genome/main/workflow/Snakefile"
    config:
        config


module scan:
    snakefile:
        "rules/scan.smk"
    config:
        config["TFBS-SCAN"]


# Import modules
use rule * from scan as scan_*


###
# Rules
###


rule all:
    message:
        """
        DEPLOYING TFBS-SCAN...
        """
    input:
        rules.scan_all.input,
    default_target: True
