# TFBS-Scan module parameters
TFBS-SCAN:
  # Target TFs to scan against. Format: [name]|[profile]|[length]
  TARGETS:
    - AR|MA0007.3|17

# PWMScan module parameters
PWMScan:
  # Path to uncompiled programs
  MATRIX_PROB: resources/software/PWMScan/matrix_prob.c
  MATRIX_SCAN: resources/software/PWMScan/matrix_scan.c

# Genome module parameters
GENOME:
  # Genome build
  ASSEMBLY: hg38
  # Genome host
  PROVIDER: UCSC
  # Regex filtering - filter FASTA to main chromosomes
  FILTER: chr[0-9XY]+$
  # Target installation directory
  OUTDIR: resources/data/genome
