# TFBS-Scan module parameters
TFBS-SCAN:
  # Target TFs to scan against. Format: [name]|[profile]|[length]
  TARGETS:
    - AR|MA0007.3|17

# PWMScan module parameters
PWMScan:
  # Path to uncompiled programs
  MATRIX_PROB: resources/software/PWMScan/matrix_prob.c
  MATRIX_SCAN: resources/software/PWMScan/matrix_scan.c

# Genome module parameters
GENOME:
  # Genome build
  BUILDS:
    - hg38
  # Genome host
  PROVIDER: UCSC
  # Regex filtering - filter FASTA to main chromosomes
  FILTER: chr[0-9XY]+$
  # Target installation directory
  OUTDIR: resources/data/genome
  # Blacklist URLs
  BLACKLIST_HG19: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg19-blacklist.v2.bed.gz
  BLACKLIST_HG38: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg38-blacklist.v2.bed.gz

GENCODE:
  # Genome build
  BUILDS:
    - hg38
  # Size of window on TSS to define promoters
  PROMOTER_WINDOW: 2000
  # Gencode URLS
  GENCODE_URLS:
    hg19: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh37_mapping/gencode.v44lift37.basic.annotation.gtf.gz
    hg38: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.basic.annotation.gtf.gz
  # Chromosome size form UCSC URLS
  UCSC_URLS:
    hg19: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes
    hg38: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chrom.sizes
